
package com.mkyong.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ImageServerImplService", 
		targetNamespace = "http://ws.mkyong.com/", 
		wsdlLocation = "http://localhost:9999/ws/image?wsdl")
public class ImageServerImplService
    extends Service
{

    private final static URL IMAGESERVERIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9999/ws/image?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        IMAGESERVERIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ImageServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageServerImplService() {
        super(IMAGESERVERIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.mkyong.com/", "ImageServerImplService"));
    }

    /**
     * 
     * @return
     *     returns ImageServer
     */
    @WebEndpoint(name = "ImageServerImplPort")
    public ImageServer getImageServerImplPort() {
        return (ImageServer)super.getPort(new QName("http://ws.mkyong.com/", "ImageServerImplPort"), ImageServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImageServer
     */
    @WebEndpoint(name = "ImageServerImplPort")
    public ImageServer getImageServerImplPort(WebServiceFeature... features) {
        return (ImageServer)super.getPort(new QName("http://ws.mkyong.com/", "ImageServerImplPort"), ImageServer.class, features);
    }

}
