
package com.mkyong.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServerInfo", targetNamespace = "http://ws.mkyong.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerInfo {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerName", targetNamespace = "http://ws.mkyong.com/", className = "com.mkyong.ws.GetServerName")
    @ResponseWrapper(localName = "getServerNameResponse", targetNamespace = "http://ws.mkyong.com/", className = "com.mkyong.ws.GetServerNameResponse")
    public String getServerName();

}
